apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: reporting-redis
    data:
      redis-addr: cmVwb3J0aW5nLXJlZGlzLW1hc3Rlcjo2Mzc5
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: reporting
    spec:
      template:
        spec:
          containers:
          - name: rep
            env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redis-addr
                  name: reporting-redis
            - name: REDIS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: reporting-redis
