apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generators
patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Deployment
      name: ?chronos
    path: ../patches/global-mongodb-secret.yaml
