apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: groups
spec:
  template:
    spec:
      containers:
      - name: groups
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: qliksense-mongoconfig
