#!/bin/bash
set -e
  
file=$1
valuesFile=`yq r "$file" valuesFile`
FILEVAL="$(mktemp)"
  
if [[ -f $valuesFile ]]; then
  cat "$valuesFile" | yq p - values > $FILEVAL
else
  echo "Error: values.tml.yaml is not found"
  exit 1
fi

index=0
errno=0
TMP_DIR=$(mktemp -d)
 
allresources=`cat`
echo "$allresources" | yq r -d $index - &>$TMP_DIR/allresources.yaml || errno=$?
if [ $errno -ne 0 ]; then
  echo "Error: Not a valid yaml file"
  exit 1
fi

allresources=$(yq m $TMP_DIR/allresources.yaml $FILEVAL)
echo "$allresources" | yq r -d $index -
