apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-prep
spec:
  template:
    spec:
      containers:
      - name: data-prep 
        env:
        - name: DPS_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-addr
              name: redis-secret
        - name: DPS_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-secret
