apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: qix-datafiles
spec:
  template:
    spec:
      containers:
      - name: qix-datafiles
        env:
        - name: MONGO__URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: qliksense-mongoconfig
