apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qix-sessions 
spec:
  template:
    spec:
      containers:
      - name: qix-sessions 
        env:
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              key: redis-addr
              name: redis-secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-secret
