apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: odag
spec:
  template:
    spec:
      containers:
      - name: odag 
        env:
        - name: SELF_SIGNING_PRIVATE_KEY 
          value: |
            -----BEGIN EC PRIVATE KEY-----
            MIGkAgEBBDDvsPODgxQg8clxdqlvPsIbwvNuBaCGbkaPjafU4IwVsW3r5fy4LsEI
            fK1YwpXah0KgBwYFK4EEACKhZANiAAS5oTJjOOhEpiqEs7CXBY5dHgoOTrAwCWGU
            4FvOLQdll67bmNOG/VXe4R1eEgUfzt52ShUrf7MUDcE5gMcCnbb/Wh6PBRGNRHkG
            kdsC5ehTvAauo+NyHw+x3uCkXlYfxc4=
            -----END EC PRIVATE KEY-----
