apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generators
patchesJson6902:
  - target:
      version: v1
      kind: Secret
      name: qliksense-mongoconfig
    path: mongoconfig.yaml