apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: data-prep-redis
    data:
      redis-addr: ZGF0YS1wcmVwLXJlZGlzLW1hc3Rlcjo2Mzc5
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: data-prep
    spec:
      template:
        spec:
          containers:
          - name: data-prep 
            env:
            - name: DPS_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redis-addr
                  name: data-prep-redis
            - name: DPS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: data-prep-redis
