apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: qix-sessions-redis
    data:
      redis-addr: cWl4LXNlc3Npb25zLXJlZGlzLW1hc3Rlcjo2Mzc5
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: qix-sessions 
    spec:
      template:
        spec:
          containers:
          - name: qix-sessions 
            env:
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  key: redis-addr
                  name: qix-sessions-redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: qix-sessions-redis
