apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronos-worker
spec:
  template:
    spec:
      containers:
      - name: chronos-worker
        env:
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              key: redis-addr
              name: redis-secret
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-secret
