apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: resource-library
spec:
  template:
    spec:
      containers:
      - name: resource-library
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: qliksense-mongoconfig
