apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reporting
spec:
  template:
    spec:
      containers:
      - name: rep
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-addr
              name: redis-secret
        - name: REDIS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-secret
