apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: dcaas-redis
    data:
      redis-addr: ZGNhYXMtcmVkaXMtbWFzdGVyOjYzNzk 
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: dcaas
    spec:
      template:
        spec:
          containers:
          - name: chronos
            env:
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  key: redis-addr
                  name: chronos-redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: chronos-redis
