apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generators
patchesJson6902:
  - target:
      version: v1
      kind: Secret
      name: qix-sessions-redis-secret
    path: redis-secret-patch.yaml
