apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: policy-decisions
spec:
  template:
    spec:
      containers:
      - name: policy-decisions
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: qliksense-mongoconfig
