apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: edge-auth
spec:
  template:
    spec:
      containers:
      - name: edge-auth
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: qliksense-mongoconfig
