apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - generators
transformers:
  - transformers
patches:
  - path: maincontainer.yaml
    target:
      kind: Deployment
      name: resource-library