apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: licenses
spec:
  template:
    spec:
      containers:
      - name: licenses
        env:
        - name: LICENSES_MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: qliksense-mongoconfig
