apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qliksense
resources:
  - ../../values 
patchesStrategicMerge:
  - devmode.yaml
  - acceptEULA.yaml
  - releaseNamespace.yaml
